{
    "openapi": "3.0.1",
    "info": {
        "title": "API do Banco hzhong",
        "description": "A API do Banco hzhong é uma plataforma que permite realizar operações bancárias, incluindo autenticação de usuários, atualização de informações de usuários, consulta de métricas financeiras e realização de transações. Esta documentação fornece informações detalhadas sobre como usar a API e suas funcionalidades.",
        "version": "3.0.1",
        "termsOfService": "https://seusite.com/terms-of-service",
        "contact": {
          "name": "Amanda (Desenvolvedora Plena)",
          "email": "amandalfs57@gmail.com",
          "url": "https://www.linkedin.com/in/amanda-rodrigues-dfbd/"
        },
        "license": {
          "name": "Licença de Uso",
          "url": "https://seusite.com/license"
        }
      },
      "externalDocs": {
        "description": "Documentação Adicional",
        "url": "https://seusite.com/docs"
    },
    "components": {
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      }
    },
    "servers": [
          {
            "url": "http://localhost:8020",
            "description": "Servidor de Desenvolvimento"
          },
          {
            "url": "https://api-test.example.com",
            "description": "Servidor de Teste"
          },
          {
            "url": "https://api-prod.example.com",
            "description": "Servidor de Produção"
          }
    ],   
    "paths": {
        "/users": {
            "post": {
            "tags": ["accounts"],
            "summary": "Criação de Usuários",
            "description": "Criação de um novo usuário.",
            "requestBody": {
                "content": {
                "application/json": {
                    "schema": {
                    "type": "object",
                    "properties": {
                        "username": {
                        "type": "string"
                        },
                        "name": {
                        "type": "string"
                        },
                        "email": {
                        "type": "string"
                        },
                        "nasc": {
                        "type": "string"
                        },
                        "typeaccont": {
                        "type": "string"
                        }
                    },
                    "example": {
                        "username": "UsuarioTest",
                        "name": "Usuario Test",
                        "email": "usuario57@test.com",
                        "nasc": "02-10-2003",
                        "typeaccont": "poupanca"
                    }
                    }
                }
                }
            },
            "parameters": [
                {
                "name": "password",
                "in": "header",
                "description": "Primeira senha",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "12345678"
                },
                {
                "name": "passwordconfirmation",
                "in": "header",
                "description": "Repita a senha",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "12345678"
                },
                {
                "name": "cpf",
                "in": "header",
                "description": "Coloque o CPF válido",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "12603863096"
                }
            ],
            "responses": {
                "400": {
                "description": "Já existe uma conta"
                },
                "201": {
                "description": "Conta criada",
                "content": {
                    "text/plain": {
                    "schema": {
                        "type": "string"
                    },
                    "example": "created"
                    }
                }
                }
            }
            }
        },  
        "/users/sessions": {
            "post": {
              "tags": ["accounts"],
              "summary": "Login do Usuário",
              "description": "Criando uma sessão para o usuário.",
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      },
                      "example": {
                        "username": "userTest1",
                        "password": "12345678"
                      }
                    }
                  }
                }
              },
              "responses": {
                "202": {
                  "description": "Login bem-sucedido.",
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "token": {
                            "type": "string"
                          }
                        },
                        "example": {
                          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQ4NTIxNTAsImV4cCI6MTY4NDkzODU1MCwic3ViIjoiMiJ9.lWUgvkjnemvlehpivcnepgOYbSdsovbjweblsYXS8kRXkN5i6Qb6jgGvokDpoiircpx63I"
                        }
                      }
                    }
                  }
                },
                "401": {
                  "description": "Senha ou nome de usuário incorretos."
                }
              }
            }
        },
        "/users/show": {
            "get": {
            "tags": ["accounts"],
            "summary": "Infos de Usuário",
            "description": "Pegar informações de usuário.",
            "security": [
              {
                "bearerAuth": []
              }
            ],
            "responses": {
                "404": {
                "description": "Usuário não encontrado."
                },
                "200": {
                "description": "Sucesso - Informações do usuário.",
                "content": {
                    "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                        "userSend": {
                            "type": "object",
                            "properties": {
                            "name": {
                                "type": "string"
                            },
                            "username": {
                                "type": "string"
                            },
                            "saldo": {
                                "type": "number"
                            },
                            "typeaccont": {
                                "type": "string"
                            },
                            "keypix": {
                                "type": "string"
                            }
                            }
                        },
                        "extracts": {
                            "type": "array",
                            "items": {
                            "type": "object",
                            "properties": {
                                "tipo": {
                                "type": "string"
                                },
                                "saldo": {
                                "type": "number"
                                },
                                "data": {
                                "type": "string"
                                },
                                "descricao": {
                                "type": "string"
                                }
                            }
                            }
                        }
                      },
                        "example": {
                        "userSend": {
                            "name": "user Test",
                            "username": "userTestSuper",
                            "saldo": 5000,
                            "typeaccont": "poupanca",
                            "keypix": null
                        },
                        "extracts": [
                            {
                            "tipo": "saque",
                            "saldo": 258,
                            "data": "05/05/2023 12:30",
                            "descricao": "Você sacou R$258,00"
                            },
                            {
                            "tipo": "saque",
                            "saldo": 258,
                            "data": "05/05/2023 12:35",
                            "descricao": "Você sacou R$258,00"
                            },
                            {
                            "tipo": "saque",
                            "saldo": 258,
                            "data": "05/05/2023 12:40",
                            "descricao": "Você sacou R$258,00"
                            }
                        ]
                        }
                    }
                    }
                }
                }
            }
            }
        },
        "/users/metrics": {
          "get": {
            "summary": "Obter métricas de usuário",
            "tags": ["accounts"],
            "description": "Obtém as métricas mensais de renda e despesas do usuário.",
            "security": [
              {
                "bearerAuth": []
              }
            ],
            "responses": {
              "200": {
                "description": "Sucesso",
                "schema": {
                  "type": "object",
                  "properties": {
                    "params": {
                      "type": "object",
                      "properties": {
                        "monthlyIncome": {
                          "type": "number",
                          "description": "Renda mensal do usuário."
                        },
                        "monthlyExpenses": {
                          "type": "number",
                          "description": "Despesas mensais do usuário."
                        }
                      },
                      "examples": {
                        "application/json": {
                          "params": {
                            "monthlyIncome": 500,
                            "monthlyExpenses": 300
                          }
                        }
                      }
                    }
                  }
                }
              },
              "404": {
                "description": "Não encontrado",
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Mensagem de erro."
                    }
                  }
                }
              }
            }
          }
        },          
        "/users/modify": {
              "patch": {
                "tags": ["accounts"],
                "summary": "Modificação de Usuário",
                "description": "Modifica informações de um usuário existente.",
                "requestBody": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "username": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "oldPassword": {
                            "type": "string"
                          },
                          "password": {
                            "type": "string"
                          }
                        },
                        "example": {
                          "username": "new username",
                          "name": "new name",
                          "email": "new email",
                          "oldPassword": "12345678",
                          "password": "new password"
                        }
                      }
                    }
                  }
                },
                "security": [
                  {
                    "bearerAuth": []
                  }
                ],
                "responses": {
                  "200": {
                    "description": "Informações do usuário modificadas com sucesso.",
                    "content": {
                      "application/json": {
                        "schema": {
                          "type": "object",
                          "properties": {
                            "params": {
                              "type": "object",
                              "properties": {
                                "name": {
                                  "type": "string"
                                },
                                "username": {
                                  "type": "string"
                                },
                                "email": {
                                  "type": "string"
                                }
                              },
                              "example": {
                                "params": {
                                  "name": "new name",
                                  "username": "new username",
                                  "email": "new email"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
        },   
        
        "transactions/sendingMoney": {
            "patch": {
              "tags": ["transactions"],
              "summary": "Envio de Dinheiro",
              "description": "Envio de dinheiro para outro usuário.",
              "requestBody": {
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "deposit": {
                          "type": "number"
                        },
                        "keypix": {
                          "type": "string"
                        }
                      },
                      "example": {
                        "deposit": 50,
                        "keypix": "vbsvSBOV4554-fdbhkjndfpbad-jbkvdfvfbvkdoutrs"
                      }
                    }
                  }
                }
              },
              "security": [
                {
                  "bearerAuth": []
                }
              ],
              "responses": {
                "400": {
                  "description": "Valor inválido",
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "msg": {
                            "type": "string"
                          }
                        }
                      },
                      "examples": {
                        "Valor inválido": {
                          "value": {
                            "msg": "Valor inválido"
                          }
                        },
                        "Sua conta do tipo {type} atingiu o limite diário de R${limit.toFixed(2)}": {
                          "value": {
                            "msg": "Sua conta do tipo poupança atingiu o limite diário de R$1000.00"
                          }
                        },
                        "Você não pode enviar dinheiro para você": {
                          "value": {
                            "msg": "Você não pode enviar dinheiro para você"
                          }
                        },
                        "A chave pix é inválida": {
                          "value": {
                            "msg": "A chave pix é inválida"
                          }
                        }
                      }
                    }
                  }
                },
                "401": {
                  "description": "Você não tem saldo suficiente",
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "msg": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "msg": "Você não tem saldo suficiente"
                      }
                    }
                  }
                },
                "403": {
                  "description": "Sua conta do tipo {type} tem um limite de R$${limit}",
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "msg": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "msg": "Sua conta do tipo poupança tem um limite de R$1000"
                      }
                    }
                  }
                },
                "201": {
                  "description": "Sucesso - Informações da transação.",
                  "content": {
                    "application/json": {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "extracts": {
                            "type": "object",
                            "properties": {
                              "send": {
                                "type": "object",
                                "properties": {
                                  "id_user": {
                                    "type": "number"
                                  },
                                  "name": {
                                    "type": "string"
                                  },
                                  "tipo": {
                                    "type": "string"
                                  },
                                  "saldo": {
                                    "type": "number"
                                  },
                                  "data": {
                                    "type": "string"
                                  },
                                  "descricao": {
                                    "type": "string"
                                  }
                                }
                              },
                              "receive": {
                                "type": "object",
                                "properties": {
                                  "id_user": {
                                    "type": "number"
                                  },
                                  "name": {
                                    "type": "string"
                                  },
                                  "tipo": {
                                    "type": "string"
                                  },
                                  "saldo": {
                                    "type": "number"
                                  },
                                  "data": {
                                    "type": "string"
                                  },
                                  "descricao": {
                                    "type": "string"
                                  }
                                }
                              }
                            }
                          }
                        },
                        "example": {
                          "extracts": {
                            "send": {
                              "id_user": 1,
                              "name": "user Test",
                              "tipo": "transferência(envio)",
                              "saldo": 50,
                              "data": "05/05/2023 12:30",
                              "descricao": "Você transferiu R$50,00 para test2"
                            },
                            "receive": {
                              "id_user": 2,
                              "name": "user Test2",
                              "tipo": "transferência(recebido)",
                              "saldo": 50,
                              "data": "05/05/2023 12:35",
                              "descricao": "Você recebeu R$50,00 de test"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
        },          
        "transactions/deposit": {
          "patch": {
            "tags": ["transactions"],
            "summary": "Depósito de Dinheiro",
            "description": "Depósito de dinheiro.",
            "requestBody": {
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "deposit": {
                        "type": "number"
                      }
                    },
                    "example": {
                      "deposit": 58
                    }
                  }
                }
              }
            },
            "security": [
              {
                "bearerAuth": []
              }
            ],
            "responses": {
              "400": {
                "description": "Saldo inválido",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "msg": {
                          "type": "string"
                        }
                      }
                    },
                    "example": {
                      "msg": "Saldo inválido"
                    }
                  }
                }
              },
              "200": {
                "description": "Depósito efetuado com sucesso",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "tipo": {
                          "type": "string"
                        },
                        "saldo": {
                          "type": "number"
                        }
                      }
                    },
                    "example": {
                      "name": "Usuario Test",
                      "tipo": "deposito",
                      "saldo": 500
                    }
                  }
                }
              },
              "404": {
                "description": "Recurso não encontrado",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "msg": {
                          "type": "string"
                        }
                      }
                    },
                    "example": {
                      "msg": "Recurso não encontrado"
                    }
                  }
                }
              }
            }
          }
        },        
        "transactions/withdraw":{
            "patch":
            {
                "tags": ["transactions"],
                "summary": "Saque de dinheiro",
                "description": "Saque de dinheiro do usuário",
                "requestBody":
                {
                    "content":
                    {
                        "application/json":
                        {
                            "schema":
                            {
                                "type": "object",
                                "properties":
                                {
                                    "withdraw":
                                    {
                                        "type": "number"
                                    }
                                },
                                "example":
                                {
                                    "withdraw": 50
                                }
                            }
                        }
                    }
                },
                "security": [
                  {
                    "bearerAuth": []
                  }
                ],
                "responses":
                {
                    "200":
                    {
                        "description": "Saque efetuado com sucesso",
                        "content":
                        {
                            "application/json":
                            {
                                "example":
                                {
                                    "params":
                                    {
                                        "extratoNew":
                                        {
                                            "name": "Usuario Test",
                                            "tipo": "Saque",
                                            "saldo": 300
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                      "description": "Valor inválido",
                      "content": {
                        "application/json": {
                          "schema": {
                            "type": "object",
                            "properties": {
                              "msg": {
                                "type": "string"
                              }
                            }
                          },
                          "examples": {
                            "Valor inválido": {
                              "value": {
                                "msg": "Valor inválido"
                              }
                            },
                            "Sua conta do tipo {type} atingiu o limite diário de R${limit.toFixed(2)}": {
                              "value": {
                                "msg": "Sua conta do tipo poupança atingiu o limite diário de R$1000.00"
                              }
                            }
                          }
                        }
                      }
                    },
                    "401":
                    {
                        "description": "Você não tem saldo suficiente",
                        "content":
                        {
                            "application/json":
                            {
                                "example":
                                {
                                    "error": "Você não tem saldo suficiente",
                                    "msg": "Você não tem saldo suficiente"
                                }
                            }
                        }
                    },
                    "403":
                    {
                        "description": "Sua conta do tipo {type} tem um limite de R${limit}",
                        "content":
                        {
                            "application/json":
                            {
                                "example":
                                {
                                    "error": "sua conta do tipo ${type} tem um limite de R$${limit}",
                                    "msg": "Sua conta do tipo {type} tem um limite de R${limit}"
                                }
                            }
                        }
                    },
                    "404":
                    {
                        "description": "Recurso não encontrado",
                        "content":
                        {
                            "application/json":
                            {
                                "example":
                                {
                                    "error": "Recurso não encontrado",
                                    "msg": "Recurso não encontrado"
                                }
                            }
                        }
                    }
                }
            }
        },
        "transactions/extracts":{
          "get":{
            "tags": ["transactions"],
            "summary": "Extratos por data",
            "description": "Extratos por data específica",
            "parameters":
            [
                {
                    "name": "dateStart",
                    "in": "query",
                    "schema":
                    {
                        "type": "string",
                        "format": "date-time"
                    },
                    "example": "2023-05-02T10:30:00"
                },
                {
                    "name": "dateEnd",
                    "in": "query",
                    "schema":
                    {
                        "type": "string",
                        "format": "date-time"
                    },
                    "example": "2023-05-02T14:45:00"
                }
            ],
            "security": [
              {
                "bearerAuth": []
              }
            ],
            "responses":
            {
                "200":
                {
                    "description": "Sucesso",
                    "content":
                    {
                        "application/json":
                        {
                            "schema":
                            {
                                "type": "array",
                                "items":
                                {
                                    "type": "object",
                                    "properties":
                                    {
                                        "tipo":
                                        {
                                            "type": "string"
                                        },
                                        "saldo":
                                        {
                                            "type": "number"
                                        },
                                        "data":
                                        {
                                            "type": "string",
                                            "format": "date-time"
                                        },
                                        "descricao":
                                        {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example":
                                [
                                    {
                                        "tipo": "saque",
                                        "saldo": 258,
                                        "data": "2023-05-05T11:15:00",
                                        "descricao": "Você sacou R$258,00"
                                    },
                                    {
                                        "tipo": "saque",
                                        "saldo": 258,
                                        "data": "2023-05-05T12:30:00",
                                        "descricao": "Você sacou R$258,00"
                                    },
                                    {
                                        "tipo": "saque",
                                        "saldo": 258,
                                        "data": "2023-05-05T14:00:00",
                                        "descricao": "Você sacou R$258,00"
                                    }
                                ]
                            }
                        }
                    }
                }
            }
          }
        },
  
        "users/keys": {
          "post":{
              "tags": ["keys"],
              "summary": "Criação de chave",
              "description": "Criação de uma chave",
              "security": [
                {
                  "bearerAuth": []
                }
              ],
              "responses":
              {
                  "200":
                  {
                      "description": "Sucesso",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "keypix":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "keypix": "vbsvSBOV4554-fdbhkjndfpbad-jbkvdfvfbvkdoutrs"
                                  }
                              }
                          }
                      }
                  },
                  "400":
                  {
                      "description": "Erro na requisição",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Chave PIX já existe"
                                  }
                              }
                          }
                      }
                  },
                  "404":
                  {
                      "description": "Recurso não encontrado",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Recurso não encontrado"
                                  }
                              }
                          }
                      }
                  }
              }
          },          
          "get":{
              "tags": ["keys"],
              "summary": "Mostrar keypix",
              "description": "Obter a sua chave PIX",
              "security": [
                {
                  "bearerAuth": []
                }
              ],
              "responses":
              {
                  "200":
                  {
                      "description": "Sucesso",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "keypix":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "keypix": "vbsvSBOV4554-fdbhkjndfpbad-jbkvdfvfbvkdoutrs"
                                  }
                              }
                          }
                      }
                  },
                  "400":
                  {
                      "description": "Erro na requisição",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Você não tem uma chave PIX"
                                  }
                              }
                          }
                      }
                  },
                  "404":
                  {
                      "description": "Recurso não encontrado",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Chave PIX não existe"
                                  }
                              }
                          }
                      }
                  }
              }
          },          
          "delete":{
              "tags": ["keys"],
              "summary": "Excluir chave PIX",
              "description": "Exclusão de chave PIX da conta",
              "security": [
                {
                  "bearerAuth": []
                }
              ],
              "responses":
              {
                  "200":
                  {
                      "description": "Sucesso",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Chave PIX deletada com sucesso"
                                  }
                              }
                          }
                      }
                  },
                  "400":
                  {
                      "description": "Erro na requisição",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Impossível deletar uma chave que não existe"
                                  }
                              }
                          }
                      }
                  },
                  "404":
                  {
                      "description": "Recurso não encontrado",
                      "content":
                      {
                          "application/json":
                          {
                              "schema":
                              {
                                  "type": "object",
                                  "properties":
                                  {
                                      "msg":
                                      {
                                          "type": "string"
                                      }
                                  },
                                  "example":
                                  {
                                      "msg": "Chave PIX não existe"
                                  }
                              }
                          }
                      }
                  }
              }
          }  
        }
    }
}
